### PR TITLE
Make event sensitivity configurable, misc optimizations

### PR DESCRIPTION
**Pull request by iamahuman**
* src/vue-pull-to.vue
    - Allow component user to attach and detach scroll and touch
      event handlers dynamically via `isTouchSensitive` and
      `isScrollSensitive`.
    - Do not reset `transition` and keep it as is; `transitionend` event
      would be more reliable (inactive browser window inhibits
      the progress of animations but not timers), and it doesn't
      repeat itself anyway.
    - Break down CSS `transition` property shorthand into
      sub-properties, and move invariable ones into stylesheets.
    - Smoother pull (scroll) animation
    - Use `translate()` instead of full-blown `translate3d()`.
    - Use Vue `$refs` instead of `Element.querySelector`.
    - Miscellaneous clean-ups and optimizations
 * src/utils.js
    - The throttle function used to invoke `clearTimeout` on timeout IDs
      that have already expired.  The spec only mentions that the newly
      allocated ID is only unique among the active timer lists, not all
      IDs that have ever been allocated since navigation to the page.
    - Use `this` and `arguments` directly for `Function#apply`, and
      convert arguments to Array for delayed procedure call.
 * test/unit/specs/dom.spec.js
    - Use Vue `$refs` instead of `Element.querySelector`.
 * test/unit/specs/event.spec.js
    - Use Vue `$refs` instead of `Element.querySelector`.
    - Added relevant test cases.
 * README*.md
    - Added relevant property descriptions.

### CODE REVIEW

**Comment by iamahuman** [comment]
(DO NOT MERGE)

**Comment by iamahuman** [comment]
:heavy_check_mark: resolved

**Comment by stackjie** [comment]
thx, let me confirm

**Comment by stackjie** [comment]
🎉  Merged

**Pull request merged**
